name: Security

on:
  push:
  pull_request:
  # Run this workflow every Monday at 6:00.
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: 'Security check'
    runs-on: ubuntu-latest

    # Don't run the cronjob in this workflow on forks.
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'streamcart')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This action checks the `composer.lock` file against known security vulnerabilities in the dependencies.
      # https://github.com/marketplace/actions/the-php-security-checker
      - name: Run Security Check
        uses: symfonycorp/security-checker-action@v5